package com.myfschool.common.exception;

public enum ErrorCode {
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    INVALID_REQUEST,
    RESOURCE_NOT_FOUND,
    BUSINESS_RULE_VIOLATION,
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    AUTH_ACCOUNT_LOCKED,
    AUTH_ACCOUNT_INACTIVE,
    AUTH_PASSWORD_RESET_REQUIRED,
    AUTH_ACTIVE_ROLE_REQUIRED,
    AUTH_ROLE_NOT_AVAILABLE,
    INTERNAL_SERVER_ERROR
}
